Controllers/API/StudentModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using reviseAuthentication.Data;
using reviseAuthentication.Models;

namespace reviseAuthentication.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class StudentModelsController : ControllerBase
    {
        private readonly MyDbContext _context;

        public StudentModelsController(MyDbContext context)
        {
            _context = context;
        }

        // GET: api/StudentModels
        [HttpGet]
        public async Task<ActionResult<IEnumerable<StudentModel>>> GetStudentModel()
        {
          if (_context.StudentModel == null)
          {
              return NotFound();
          }
            return await _context.StudentModel.ToListAsync();
        }

        // GET: api/StudentModels/5
        [HttpGet("{id}")]
        public async Task<ActionResult<StudentModel>> GetStudentModel(int id)
        {
          if (_context.StudentModel == null)
          {
              return NotFound();
          }
            var studentModel = await _context.StudentModel.FindAsync(id);

            if (studentModel == null)
            {
                return NotFound();
            }

            return studentModel;
        }

        // PUT: api/StudentModels/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutStudentModel(int id, StudentModel studentModel)
        {
            if (id != studentModel.Id)
            {
                return BadRequest();
            }

            _context.Entry(studentModel).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StudentModelExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/StudentModels
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<StudentModel>> PostStudentModel(StudentModel studentModel)
        {
          if (_context.StudentModel == null)
          {
              return Problem("Entity set 'MyDbContext.StudentModel'  is null.");
          }
            _context.StudentModel.Add(studentModel);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetStudentModel", new { id = studentModel.Id }, studentModel);
        }

        // DELETE: api/StudentModels/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteStudentModel(int id)
        {
            if (_context.StudentModel == null)
            {
                return NotFound();
            }
            var studentModel = await _context.StudentModel.FindAsync(id);
            if (studentModel == null)
            {
                return NotFound();
            }

            _context.StudentModel.Remove(studentModel);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool StudentModelExists(int id)
        {
            return (_context.StudentModel?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/EmailSendController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using reviseAuthentication.Models;
using reviseAuthentication.Settings;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;

namespace reviseAuthentication.Controllers
{
    public class EmailSendController : Controller
    {
        private readonly MailSettings _emailSetting;

        public EmailSendController(IOptions<MailSettings> emailSetting)
        {

            _emailSetting = emailSetting.Value;
        }
        public IActionResult Email()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Email(string to, string subject, string description)
        {
            try
            {
                // Create the MailMessage object
                MailMessage mail = new MailMessage();
                mail.From = new MailAddress(_emailSetting.UserName);
                mail.To.Add(to);
                mail.Subject = subject;
                mail.Body = description;
                mail.IsBodyHtml = true; // Set to true if your body contains HTML content

                // Configure the SMTP client
                SmtpClient smtpClient = new SmtpClient(_emailSetting.SmtpServer, _emailSetting.SmtpPort);
                smtpClient.EnableSsl = _emailSetting.EnableSsl;
                smtpClient.Credentials = new NetworkCredential(_emailSetting.UserName, _emailSetting.Password);

                // Send the email
                smtpClient.Send(mail);

                // Optionally, you can redirect to a success page or return a JSON response
                /*  return Json(new { success = true, message = "Email sent successfully." });*/
                ModelState.Clear();
                TempData["EmailSent"] = "Mail sent successfully";
                return View();


            }
            catch (Exception)
            {
                // Handle exceptions here, you can redirect to an error page or return a JSON response
                TempData["EmailError"] = "Error while sending mail";
            }
            return View();

        }


    }
}

Views/Shared/Components/SearchBar/SearchBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace reviseAuthentication.Views.Shared.Components.SearchBar
{
    public class SearchBarViewComponent : ViewComponent
    {
        public SearchBarViewComponent()
        {

        }

        public IViewComponentResult Invoke(SPager SearchPager)
        {
            return View("Default", SearchPager);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>


@using System.Security.Claims;
@inject IHttpContextAccessor _httpContext

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - reviseAuthentication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/reviseAuthentication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>

        <span>
            @{
                var username = _httpContext.HttpContext.User?.FindFirstValue("UserName");
            }
        </span>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">reviseAuthentication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if (!string.IsNullOrEmpty(username))
                        {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="StudentModels" asp-action="Index">Student</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EmailSend" asp-action="Email">Send Email</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Signout">Signout</a>
                            </li>
                        }

                         else{
                            <li class="nav-item justify-content-end">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Signup">Signup</a>
                            </li>
                            
                            <li class="nav-item">
                            <a class="nav-link text-dark justify-content-end" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                         }
                       
                    </ul>
                </div>

                @if (!string.IsNullOrEmpty(username))
                {
                    @*Display the username(Email) after the Login in header*@
                    <span class="btn btn-outline-dark">User: @username</span>
                }

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name ="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - reviseAuthentication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if (TempData["Signup"]!=null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Signup"]');
    </script>
}

@if (TempData["SignupError"]!=null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["SignupError"]');
    </script>
}

@if (TempData["Login"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Login"]');
    </script>
}
@if (TempData["LoginError"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["LoginError"]');
    </script>
}
    @if (TempData["Signout"]!=null)
    {
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
        <script type="text/javascript">
            toastr.success('@TempData["Signout"]');
        </script>
      }

@if (TempData["EmailSent"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["EmailSent"]');
    </script>
}
@if (TempData["EmailError"]!=null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["EmailError"]');
    </script>
}