Models/StudentModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace reviseAuthentication.Models
{
    public class StudentModel
    {
        public int Id { get; set; }

        [Filter.CustomValidation(50,5)]
        [DisplayName("Full name")]
        public string FullName { get; set; }

        public string Address { get; set; }

    }
    
}

Controllers/API/StudentModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using reviseAuthentication.Data;
using reviseAuthentication.Models;

namespace reviseAuthentication.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class StudentModelsController : ControllerBase
    {
        private readonly MyDbContext _context;

        public StudentModelsController(MyDbContext context)
        {
            _context = context;
        }

        // GET: api/StudentModels
        [HttpGet]
        public async Task<ActionResult<IEnumerable<StudentModel>>> GetStudentModel()
        {
          if (_context.StudentModel == null)
          {
              return NotFound();
          }
            return await _context.StudentModel.ToListAsync();
        }

        // GET: api/StudentModels/5
        [HttpGet("{id}")]
        public async Task<ActionResult<StudentModel>> GetStudentModel(int id)
        {
          if (_context.StudentModel == null)
          {
              return NotFound();
          }
            var studentModel = await _context.StudentModel.FindAsync(id);

            if (studentModel == null)
            {
                return NotFound();
            }

            return studentModel;
        }

        // PUT: api/StudentModels/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutStudentModel(int id, StudentModel studentModel)
        {
            if (id != studentModel.Id)
            {
                return BadRequest();
            }

            _context.Entry(studentModel).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StudentModelExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/StudentModels
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<StudentModel>> PostStudentModel(StudentModel studentModel)
        {
          if (_context.StudentModel == null)
          {
              return Problem("Entity set 'MyDbContext.StudentModel'  is null.");
          }
            _context.StudentModel.Add(studentModel);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetStudentModel", new { id = studentModel.Id }, studentModel);
        }

        // DELETE: api/StudentModels/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteStudentModel(int id)
        {
            if (_context.StudentModel == null)
            {
                return NotFound();
            }
            var studentModel = await _context.StudentModel.FindAsync(id);
            if (studentModel == null)
            {
                return NotFound();
            }

            _context.StudentModel.Remove(studentModel);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool StudentModelExists(int id)
        {
            return (_context.StudentModel?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/StudentModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using reviseAuthentication.Data;
using reviseAuthentication.Models;
using reviseAuthentication.Views.Shared.Components.SearchBar;

namespace reviseAuthentication.Controllers
{
    public class StudentModelsController : Controller
    {
        private readonly MyDbContext _context;

        public StudentModelsController(MyDbContext context)
        {
            _context = context;
        }

        // GET: StudentModels
        public IActionResult Index(string SearchText = "", int pg=1)
        {
            List<StudentModel> StudentModel = _context.StudentModel.ToList();

            //Pagination
           
            if (SearchText != "" && SearchText != null)
            {
                     StudentModel =  _context.StudentModel
                    .Where(s => s.FullName.Contains(SearchText))
                    .ToList();
            }
            else
            

                StudentModel = _context.StudentModel.ToList();
                SPager SearchPager = new SPager() { Action = "Index", Controller = "StudentModels", SearchText = SearchText };
                ViewBag.SearchPager = SearchPager;

            const int pageSize = 5;
            if (pg < 1)
                pg = 1;

            int rescCount = StudentModel.Count();
            var pager = new Pager(rescCount, pg, pageSize);
            int recSkip = (pg-1) * pageSize;
            var data = StudentModel.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;


            return View(data);
            
        }

        // GET: StudentModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.StudentModel == null)
            {
                return NotFound();
            }

            var studentModel = await _context.StudentModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (studentModel == null)
            {
                return NotFound();
            }

            return View(studentModel);
        }

        // GET: StudentModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StudentModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,Address")] StudentModel studentModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(studentModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(studentModel);
        }

        // GET: StudentModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.StudentModel == null)
            {
                return NotFound();
            }

            var studentModel = await _context.StudentModel.FindAsync(id);
            if (studentModel == null)
            {
                return NotFound();
            }
            return View(studentModel);
        }

        // POST: StudentModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,Address")] StudentModel studentModel)
        {
            if (id != studentModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(studentModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentModelExists(studentModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(studentModel);
        }

        // GET: StudentModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.StudentModel == null)
            {
                return NotFound();
            }

            var studentModel = await _context.StudentModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (studentModel == null)
            {
                return NotFound();
            }

            return View(studentModel);
        }

        // POST: StudentModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.StudentModel == null)
            {
                return Problem("Entity set 'MyDbContext.StudentModel'  is null.");
            }
            var studentModel = await _context.StudentModel.FindAsync(id);
            if (studentModel != null)
            {
                _context.StudentModel.Remove(studentModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentModelExists(int id)
        {
          return (_context.StudentModel?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/Components/SearchBar/SearchBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace reviseAuthentication.Views.Shared.Components.SearchBar
{
    public class SearchBarViewComponent : ViewComponent
    {
        public SearchBarViewComponent()
        {

        }

        public IViewComponentResult Invoke(SPager SearchPager)
        {
            return View("Default", SearchPager);
        }
    }
}

Views/StudentModels/Create.cshtml
@model reviseAuthentication.Models.StudentModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>StudentModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/StudentModels/Delete.cshtml
@model reviseAuthentication.Models.StudentModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StudentModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/StudentModels/Details.cshtml
@model reviseAuthentication.Models.StudentModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>StudentModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/StudentModels/Edit.cshtml
@model reviseAuthentication.Models.StudentModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>StudentModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/StudentModels/Index.cshtml
@model IEnumerable<reviseAuthentication.Models.StudentModel>

@{
    ViewData["Title"] = "Students";

    //for displaying the S.No.



    //Pagination
    Pager pager = new Pager();
    var pagesize = pager.PageSize;
    var CurrentPage = pager.CurrentPage;

    int intSno = (pager.PageSize) * ((pager.CurrentPage)-1);
    int pageNo = 0;
    if(ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }

    
}


<vc:search-bar search-pager="@ViewBag.SearchPager"></vc:search-bar>

<h1 style="font-family:'Netflix Sans Icon';">Students</h1>

<br />

<hr />


<p>
    <a asp-action="Create" style="text-decoration:none">New Student?</a>
</p>
<table class="table border-dark table-hover">
    <thead>
        <tr>
            <th class="text-center">
                SN.
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
            //Increasing the numbering of SN. by 1

           
                intSno = intSno + 1;

           
            <tr>
                <td class="text-center">
                    @intSno
                </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.Address)
            </td>
             <td class="text-center">
                <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                <a class="btn btn-info"asp-action="Details" asp-route-id="@item.Id">Details</a> 
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>


@*Pagination*@

<div class="container">
    @if (pager.TotalPages > 0)
    {
        <ul class="pagination justify-content-center">
            @if (pager.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="StudentModels" asp-action="Index" asp-route-pg="1">First</a>
                </li>
                <li>
                    <a class="page-link" asp-controller="StudentModels" asp-action="Index" asp-route-pg="@(pager.CurrentPage-1)">Previous</a>
                </li>
            }





            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
            {
                <li class="page-item @(pge == pager.CurrentPage? "active" : "")">
                    <a class="page-link" asp-controller="StudentModels" asp-action="Index" asp-route-pg="@pge">@pge</a>
                </li>
            }   

           @* For Next and Last Button*@

            @if (pager.CurrentPage<pager.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="StudentModels" asp-action="Index" asp-route-pg="@(pager.CurrentPage + 1)">Next</a>
                </li>
                 <li class="page-item">
                    <a class="page-link" asp-controller="StudentModels" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Last</a>
                </li>
            }

       </ul>
    }


</div>